//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TACHYON.Reports.Templates {
    
    public partial class PodPerformanceReport : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "TACHYON.Reports.Templates.PodPerformanceReport.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
            this.pageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo2");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.gh_carrierName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gh_carrierName");
            this.gh_loadingDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gh_loadingDate");
            this.gh_isUploadedWithin7Days = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gh_isUploadedWithin7Days");
            this.gh_invoiceStatus = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gh_invoiceStatus");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.tableCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell5");
            this.tableCell6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell6");
            this.tableCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell7");
            this.tableCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell8");
            this.gh_shipperName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gh_shipperName");
            this.gh_waybillNumber = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gh_waybillNumber");
            this.gh_offloadingDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gh_offloadingDate");
            this.gh_podStatus = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gh_podStatus");
            this.gd_podStatus = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gd_podStatus");
            this.gd_shipperName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gd_shipperName");
            this.gd_waybillNumber = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gd_waybillNumber");
            this.gd_offloadingDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("gd_offloadingDate");

            // Parameters
            this.ReportId = reportInitializer.GetParameter("ReportId");

            // Data Sources
            this.jsonDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Json.JsonDataSource>("jsonDataSource1");

            // Styles
            this.Title = reportInitializer.GetStyle("Title");
            this.DetailCaption1 = reportInitializer.GetStyle("DetailCaption1");
            this.DetailData1 = reportInitializer.GetStyle("DetailData1");
            this.DetailData3_Odd = reportInitializer.GetStyle("DetailData3_Odd");
            this.PageInfo = reportInitializer.GetStyle("PageInfo");
        }
        private DevExpress.DataAccess.Json.JsonDataSource jsonDataSource1;
        private DevExpress.XtraReports.Parameters.Parameter ReportId;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo2;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell gh_carrierName;
        private DevExpress.XtraReports.UI.XRTableCell gh_loadingDate;
        private DevExpress.XtraReports.UI.XRTableCell gh_isUploadedWithin7Days;
        private DevExpress.XtraReports.UI.XRTableCell gh_invoiceStatus;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell5;
        private DevExpress.XtraReports.UI.XRTableCell tableCell6;
        private DevExpress.XtraReports.UI.XRTableCell tableCell7;
        private DevExpress.XtraReports.UI.XRTableCell tableCell8;
        private DevExpress.XtraReports.UI.XRControlStyle Title;
        private DevExpress.XtraReports.UI.XRControlStyle DetailCaption1;
        private DevExpress.XtraReports.UI.XRControlStyle DetailData1;
        private DevExpress.XtraReports.UI.XRControlStyle DetailData3_Odd;
        private DevExpress.XtraReports.UI.XRControlStyle PageInfo;
        private DevExpress.XtraReports.UI.XRTableCell gh_shipperName;
        private DevExpress.XtraReports.UI.XRTableCell gh_waybillNumber;
        private DevExpress.XtraReports.UI.XRTableCell gh_offloadingDate;
        private DevExpress.XtraReports.UI.XRTableCell gh_podStatus;
        private DevExpress.XtraReports.UI.XRTableCell gd_podStatus;
        private DevExpress.XtraReports.UI.XRTableCell gd_shipperName;
        private DevExpress.XtraReports.UI.XRTableCell gd_waybillNumber;
        private DevExpress.XtraReports.UI.XRTableCell gd_offloadingDate;
    }
}
