//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TACHYON.Web.Reports {
    
    public partial class TripDetailsReport : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "TACHYON.Reports.Templates.TripDetailsReport.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
            this.pageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo2");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.Header_WaybillNumber = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_WaybillNumber");
            this.Header_TripStatus = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_TripStatus");
            this.Header_OriginCity = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_OriginCity");
            this.Header_DestinationCity = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_DestinationCity");
            this.Header_RouteType = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_RouteType");
            this.Header_TruckType = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_TruckType");
            this.Header_GoodsCategory = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_GoodsCategory");
            this.Header_ShippingType = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_ShippingType");
            this.Header_NumberOfDrops = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_NumberOfDrops");
            this.Header_SubWaybills = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_SubWaybills");
            this.Header_InvoiceStatus = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_InvoiceStatus");
            this.Header_DriverName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("Header_DriverName");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.CellData_WaybillNumber = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_WaybillNumber");
            this.CellData_TripStatus = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_TripStatus");
            this.CellData_OriginCity = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_OriginCity");
            this.CellData_DestinationCtiy = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_DestinationCtiy");
            this.CellData_RouteType = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_RouteType");
            this.CellData_TruckType = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_TruckType");
            this.CellData_GoodsCategory = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_GoodsCategory");
            this.CellData_ShippingType = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_ShippingType");
            this.CellData_NumberOfDrops = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_NumberOfDrops");
            this.CellData_SubWaybills = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_SubWaybills");
            this.CellData_InvoiceStatus = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_InvoiceStatus");
            this.CellData_DriverName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("CellData_DriverName");

            // Parameters
            this.ReportId = reportInitializer.GetParameter("ReportId");

            // Data Sources
            this.jsonDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Json.JsonDataSource>("jsonDataSource1");

            // Calculated Fields
            this.FullName = reportInitializer.GetCalculatedField("FullName");

            // Styles
            this.Title = reportInitializer.GetStyle("Title");
            this.DetailCaption1 = reportInitializer.GetStyle("DetailCaption1");
            this.DetailData1 = reportInitializer.GetStyle("DetailData1");
            this.DetailData3_Odd = reportInitializer.GetStyle("DetailData3_Odd");
            this.PageInfo = reportInitializer.GetStyle("PageInfo");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo2;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell Header_WaybillNumber;
        private DevExpress.XtraReports.UI.XRTableCell Header_TripStatus;
        private DevExpress.XtraReports.UI.XRTableCell Header_OriginCity;
        private DevExpress.XtraReports.UI.XRTableCell Header_DestinationCity;
        private DevExpress.XtraReports.UI.XRTableCell Header_RouteType;
        private DevExpress.XtraReports.UI.XRTableCell Header_TruckType;
        private DevExpress.XtraReports.UI.XRTableCell Header_GoodsCategory;
        private DevExpress.XtraReports.UI.XRTableCell Header_ShippingType;
        private DevExpress.XtraReports.UI.XRTableCell Header_NumberOfDrops;
        private DevExpress.XtraReports.UI.XRTableCell Header_SubWaybills;
        private DevExpress.XtraReports.UI.XRTableCell Header_InvoiceStatus;
        private DevExpress.XtraReports.UI.XRTableCell Header_DriverName;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell CellData_WaybillNumber;
        private DevExpress.XtraReports.UI.XRTableCell CellData_TripStatus;
        private DevExpress.XtraReports.UI.XRTableCell CellData_OriginCity;
        private DevExpress.XtraReports.UI.XRTableCell CellData_DestinationCtiy;
        private DevExpress.XtraReports.UI.XRTableCell CellData_RouteType;
        private DevExpress.XtraReports.UI.XRTableCell CellData_TruckType;
        private DevExpress.XtraReports.UI.XRTableCell CellData_GoodsCategory;
        private DevExpress.XtraReports.UI.XRTableCell CellData_ShippingType;
        private DevExpress.XtraReports.UI.XRTableCell CellData_NumberOfDrops;
        private DevExpress.XtraReports.UI.XRTableCell CellData_SubWaybills;
        private DevExpress.XtraReports.UI.XRTableCell CellData_InvoiceStatus;
        private DevExpress.XtraReports.UI.XRTableCell CellData_DriverName;
        private DevExpress.XtraReports.UI.XRControlStyle Title;
        private DevExpress.XtraReports.UI.XRControlStyle DetailCaption1;
        private DevExpress.XtraReports.UI.XRControlStyle DetailData1;
        private DevExpress.XtraReports.UI.XRControlStyle DetailData3_Odd;
        private DevExpress.XtraReports.UI.XRControlStyle PageInfo;
        private DevExpress.XtraReports.UI.CalculatedField FullName;
        private DevExpress.XtraReports.Parameters.Parameter ReportId;
        private DevExpress.DataAccess.Json.JsonDataSource jsonDataSource1;
    }
}
