stages:
  - preparation
  - Build
  - release
  - sonarQube
  
### start of Preparation
Preparation:
  stage: preparation
  tags:
    - dev-runner
  script:
    - Stop-WebSite 'dev' ## stopping FrontEnd Website
    - Stop-WebSite 'dev-back' ## stopping Backend Website
  only:
    - develop
### end of Preparation
### starting Build
Project:
  stage: Build
  tags:
    - dev-runner
  script:
    - Remove-Item 'C:\inetpub\wwwroot\Tachyon\Develop' -Force -Recurse
    - cd ./aspnet-core/build
    - ./build-with-ng.ps1
  only:
    - develop
## end of build
### start of release
release:
  stage: release
  tags:
    - dev-runner
  script:
    - dir
    - Start-WebSite 'dev' ##start Backend Site
    - Start-WebSite 'dev-back' ##start fronend Site
  only:
    - develop
