stages:
  - preparation
  - Build
  - release
### start of Preparation
Preparation:
  stage: preparation
  tags:
    - dev-runner
  script:
    - Remove-Item 'C:\Users\Islam\Desktop\pureProject' -Force -Recurse
    - New-Item -Path 'C:\Users\Islam\Desktop\pureProject' -ItemType Directory
    - Copy-item -Force -Recurse -Verbose . -Destination C:\Users\Islam\Desktop\pureProject
    - Stop-WebSite 'Default Web Site' ## stopping FrontEnd Website
    - Stop-WebSite 'TachyonProdCore' ## stopping Backend Website
  only:
    - feature/CI-CD
### end of Preparation
### starting Build
Backend:
  stage: Build
  tags:
    - dev-runner
  script:
    - cd C:\Users\Islam\Desktop\pureProject\tachyon-core\aspnet-core\src\TACHYON.Web.Host
    - dotnet restore
    - dotnet publish /p:EnvironmentName=Development -o C:\inetpub\wwwroot\Tachyon\back ## dont forget to change files
    - Copy-Item -Path 'C:\Users\Islam\Desktop\backConfigrationFiler\appsettings.json' -Destination 'C:\inetpub\wwwroot\Tachyon\back' -Force
  only:
    - feature/CI-CD
## end of build
##start of build frontend
Frontend:
  stage: Build
  tags:
    - dev-runner
  script:
    - cd C:\Users\Islam\Desktop\pureProject\tachyon-core\angular
    - Copy-Item -Path 'C:\Users\Islam\Desktop\frontConfigurationFile\appconfig.json' , 'C:\Users\Islam\Desktop\frontConfigurationFile\appconfig.production.json'  -Destination C:\Users\Islam\Desktop\pureProject\tachyon-core\angular\src\assets -Force
    - Copy-Item -Path 'C:\Users\Islam\Desktop\frontConfigurationFile\web.config' -Destination C:\Users\Islam\Desktop\pureProject\tachyon-core\angular -Force
    - yarn install
    - npm run publish
    - Copy-item -Force -Recurse -Verbose ./dist -Destination C:\inetpub\wwwroot\Tachyon ## we need to change the path in the future to Develop path
  only:
    - feature/CI-CD
##end of build frontend
### start of release
release:
  stage: release
  tags:
    - dev-runner
  script:
    - dir
    - Start-WebSite 'TachyonProdCore' ##start Backend Site
    - Start-WebSite 'Default Web Site' ##start fronend Site
  only:
    - feature/CI-CD

