stages:
  - Build & Publish
### starting Build
Project:
  stage: Build & Publish
  tags:
    - production-runner
  script:
    - cd ./aspnet-core/build
    - ./build-with-ng-production.ps1
  only:
    - main-ci-test
    - main
  when: manual
## end of build
