stages:
  - preparation
  - Build
  - release
  - sonarQube
  
### start of Preparation
Preparation:
  stage: preparation
  tags:
    - dev-runner
  script:
    - Stop-WebSite 'Default Web Site' ## stopping FrontEnd Website
    - Stop-WebSite 'TachyonProdCore' ## stopping Backend Website
  only:
    - staging
### end of Preparation
### starting Build
Project:
  stage: Build
  tags:
    - dev-runner
  script:
    - Remove-Item 'C:\inetpub\wwwroot\Tachyon\outputs' -Force -Recurse
    - cd ./aspnet-core/build
    - ./build-with-ng.ps1
  only:
    - staging
## end of build
### start of release
release:
  stage: release
  tags:
    - dev-runner
  script:
    - dir
    - Start-WebSite 'TachyonProdCore' ##start Backend Site
    - Start-WebSite 'Default Web Site' ##start fronend Site
  only:
    - staging