export class DashboardCustomizationConst {
  static widgets = {
    //Shared Between All Tenants
    tenant: {
      profitShare: 'Widgets_Tenant_ProfitShare',
      memberActivity: 'Widgets_Tenant_MemberActivity',
      regionalStats: 'Widgets_Tenant_RegionalStats',
      salesSummary: 'Widgets_Tenant_SalesSummary',
      topStats: 'Widgets_Tenant_TopStats',
      generalStats: 'Widgets_Tenant_GeneralStats',
      dailySales: 'Widgets_Tenant_DailySales',
    },
    //Shipper Only Widgets
    Shipper: {
      ShipperNumberOfCompletedTripsWidget: 'Widgets_Tenant_shipper_NumberofcompletedTripsWidget',
      ShipperAcceptedVsRejectedRequestsWidget: 'Widgets_Tenant_shipper_AcceptedVsRejectedRequestsWidget',
      ShipperCompletedTripsVsPodWidget: 'Widgets_Tenant_shipper_CompletedTripsVsPodWidget',
      ShipperInvoicesVsPaidInvoicesWidget: 'Widgets_Tenant_shipper_InvoicesVsPaidInvoicesWidget',
      ShipperNextInvoiceFrequancyEndDateWidget: 'Widgets_Tenant_shipper_NextInvoiceFrequancyEndDateWidget',
      ShipperInvoiceDueDateInDaysWidget: 'Widgets_Tenant_shipper_InvoiceDueDateInDaysWidget',
      ShipperDocumentDueDateInDaysWidget: 'Widgets_Tenant_shipper_DocumentDueDateInDaysWidget',
      ShipperMostWorkedWithCarriersWidget: 'Widgets_Tenant_shipper_MostWorkedWithCarriersWidget',
      ShipperMostUsedOriginsWidget: 'Widgets_Tenant_shipper_MostUsedOriginsWidget',
      ShipperMostUsedDestinationsWidget: 'Widgets_Tenant_shipper_MostUsedDestinationsWidget',
      ShipperRequestsInMarketplaceWidget: 'Widgets_Tenant_shipper_RequestsInMarketplaceWidget',
      ShipperTrackingMapWidget: 'Widgets_Tenant_shipper_TrackingMapWidget',
    },
    //Carrier Only Widgets
    Carrier: {
      CarrierDriversActivityWidget: 'Widgets_Tenant_carrier_DriversActivityWidget',
      CarrierTrucksActivityWidget: 'Widgets_Tenant_carrier_TrucksActivityWidget',
      CarrierAcceptedVsRejectedPricingWidget: 'Widgets_Tenant_carrier_AcceptedVsRejectedPricingWidget',
      CarrierInvoicesVsPaidInvoicesWidget: 'Widgets_Tenant_carrier_InvoicesVsPaidInvoicesWidget',
      CarrierMostUsedPpWidget: 'Widgets_Tenant_carrier_MostUsedPPWidget',
      CarrierMostUsedVasWidget: 'Widgets_Tenant_carrier_MostUsedVasWidget',
      CarrierNumberOfCompletedTripsTotalMonthlyIncreaseWidget: 'Widgets_Tenant_carrier_NumberOfCompletedTripsTotalMonthlyIncreaseWidget',
      CarrierMostWorkedWithShipperWidget: 'Widgets_Tenant_carrier_MostWorkedWithShipperWidget',
      CarrierNextInvoiceFrequenctEndDateWidget: 'Widgets_Tenant_carrier_NextInvoiceFrequenctEndDateWidget',
      CarrierDueDateInDaysWidget: 'Widgets_Tenant_carrier_DueDateInDaysWidget',
      CarrierTrackingMapWidget: 'Widgets_Tenant_carrier_TrackingMapWidget',
    },
    //TachyonDealer Only Widgets
    TachyonDealer: {
      TMSNumberOfRegisteredTrucksWidget: 'Widgets_Tenant_TachyonDealer_NumberOfRegisteredTrucksWidget',
      TMSNumberOfRegisteredShippersWidget: 'Widgets_Tenant_TachyonDealer_NumberOfRegisteredShippersWidget',
      TMSNumberOfRegisteredCarriersWidget: 'Widgets_Tenant_TachyonDealer_NumberOfRegisteredCarriersWidget',
      TMSNewAccountsRegisteredWidget: 'Widgets_Tenant_TachyonDealer_NewAccountsRegisterdWidget',
      TMSNewTripsWidget: 'Widgets_Tenant_TachyonDealer_NewTripsWidget',
      TMSNumberOfDeliveredTripsWidget: 'Widgets_Tenant_TachyonDealer_NumberOfDeliverdTripsWidget',
      TMSNumberOfOngoingTripsWidget: 'Widgets_Tenant_TachyonDealer_NumberOfOngoingTripsWidget',
      TMSTruckTypeUsageWidget: 'Widgets_Tenant_TachyonDealer_TruckTypeUsageWidget',
      TMSGoodTypesUsageWidget: 'Widgets_Tenant_TachyonDealer_GoodTypesUsageWidget',
      TMSRouteTypesUsageWidget: 'Widgets_Tenant_TachyonDealer_RouteTypesUsageWidget',
      TMSMostRequestingShippersWidget: 'Widgets_Tenant_TachyonDealer_MostRequestingShippersWidget',
      TMSMostRequestedCarriersWidget: 'Widgets_Tenant_TachyonDealer_MostRequestedCarriersWidget',
      TMSTopRatedShippersWidget: 'Widgets_Tenant_TachyonDealer_TopRatedShippersWidget',
      TMSTopRatedCarriersWidget: 'Widgets_Tenant_TachyonDealer_TopRatedCarriersWidget',
      TMSWorstRatedShippersWidget: 'Widgets_Tenant_TachyonDealer_WorstRatedShippersWidget',
      TMSWorstRatedCarriersWidget: 'Widgets_Tenant_TachyonDealer_WorstRatedCarriersWidget',
      TMSUnPricedRequestsInMarketPlaceWidget: 'Widgets_Tenant_TachyonDealer_UnpricedRequestsInMarketPlaceWidget',
      TMSRequestsPricingBeforeBidEndingWidget: 'Widgets_Tenant_TachyonDealer_RequestsPricingBeforeBidEndingWidget',
      TMSRequestsPriceAcceptanceWidget: 'Widgets_Tenant_TachyonDealer_RequestsPriceAcceptanceWidget',
      TMSInvoicesPaidBeforeDueDateWidget: 'Widgets_Tenant_TachyonDealer_InvoicesPaidBeforeDureDateWidget',
      TMSNumberOfRequestsPerAreaOrCityWidget: 'Widgets_Tenant_TachyonDealer_NumberOfRequestsPerAreaOrCityWidget',
      //TachyonDealerSearchableMapWidget: 'Widgets_Tenant_TachyonDealer_SearchableMapWidget',
      //TachyonDealerRequestsHeatMapWidget: 'Widgets_Tenant_TachyonDealer_RequestsHeatMapWidget',
      //TachyonDealerNormalVsRentalRequestsWidget: 'Widgets_Tenant_TachyonDealer_NormalVsRentalRequestsWidget',
    },
    //Widgets For Host Only
    host: {
      topStats: 'Widgets_Host_TopStats',
      incomeStatistics: 'Widgets_Host_IncomeStatistics',
      editionStatistics: 'Widgets_Host_EditionStatistics',
      subscriptionExpiringTenants: 'Widgets_Host_SubscriptionExpiringTenants',
      recentTenants: 'Widgets_Host_RecentTenants',
      NumberOfRegisteredTrucksWidget: 'Widgets_Tenant_TachyonDealer_NumberOfRegisteredTrucksWidget',
      NumberOfRegisteredShippersWidget: 'Widgets_Tenant_TachyonDealer_NumberOfRegisteredShippersWidget',
      NumberOfRegisteredCarriersWidget: 'Widgets_Tenant_TachyonDealer_NumberOfRegisteredCarriersWidget',
      NewAccountsRegisteredWidget: 'Widgets_Tenant_TachyonDealer_NewAccountsRegisterdWidget',
      NewTripsWidget: 'Widgets_Tenant_TachyonDealer_NewTripsWidget',
      NumberOfDeliveredTripsWidget: 'Widgets_Tenant_TachyonDealer_NumberOfDeliverdTripsWidget',
      NumberOfOngoingTripsWidget: 'Widgets_Tenant_TachyonDealer_NumberOfOngoingTripsWidget',
      TruckTypeUsageWidget: 'Widgets_Tenant_TachyonDealer_TruckTypeUsageWidget',
      GoodTypesUsageWidget: 'Widgets_Tenant_TachyonDealer_GoodTypesUsageWidget',
      RouteTypesUsageWidget: 'Widgets_Tenant_TachyonDealer_RouteTypesUsageWidget',
      MostRequestingShippersWidget: 'Widgets_Tenant_TachyonDealer_MostRequestingShippersWidget',
      MostRequestedCarriersWidget: 'Widgets_Tenant_TachyonDealer_MostRequestedCarriersWidget',
      TopRatedShippersWidget: 'Widgets_Tenant_TachyonDealer_TopRatedShippersWidget',
      TopRatedCarriersWidget: 'Widgets_Tenant_TachyonDealer_TopRatedCarriersWidget',
      WorstRatedShippersWidget: 'Widgets_Tenant_TachyonDealer_WorstRatedShippersWidget',
      WorstRatedCarriersWidget: 'Widgets_Tenant_TachyonDealer_WorstRatedCarriersWidget',
      UnPricedRequestsInMarketPlaceWidget: 'Widgets_Tenant_TachyonDealer_UnpricedRequestsInMarketPlaceWidget',
      RequestsPricingBeforeBidEndingWidget: 'Widgets_Tenant_TachyonDealer_RequestsPricingBeforeBidEndingWidget',
      RequestsPriceAcceptanceWidget: 'Widgets_Tenant_TachyonDealer_RequestsPriceAcceptanceWidget',
      InvoicesPaidBeforeDueDateWidget: 'Widgets_Tenant_TachyonDealer_InvoicesPaidBeforeDureDateWidget',
      NumberOfRequestsPerAreaOrCityWidget: 'Widgets_Tenant_TachyonDealer_NumberOfRequestsPerAreaOrCityWidget',
      //TachyonDealerSearchableMapWidget: 'Widgets_Tenant_TachyonDealer_SearchableMapWidget',
      //TachyonDealerRequestsHeatMapWidget: 'Widgets_Tenant_TachyonDealer_RequestsHeatMapWidget',
      //TachyonDealerNormalVsRentalRequestsWidget: 'Widgets_Tenant_TachyonDealer_NormalVsRentalRequestsWidget',
    },
  };
  static filters = {
    filterDateRangePicker: 'Filters_DateRangePicker',
  };
  static dashboardNames = {
    defaultTenantDashboard: 'TenantDashboard',
    defaultHostDashboard: 'HostDashboard', //was HostDashboard
    defaultCarrierDashboard: 'CarrierDashboard',
    defaultShipperDashboard: 'ShipperDashboard',
    defaultTachyonMangedServiceDashboard: 'TachyonMangedServiceDashboard',
  };
  static Applications = {
    Angular: 'Angular',
  };
}
